# Generated by Django 5.2.1 on 2025-05-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
